/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import derby.FilmeDerby;
import derby.PessoaDerby;
import filme.Filme;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import pessoa.Pessoa;

/**
 *
 * @author Jamex
 */
public class Admin extends javax.swing.JFrame {

    PessoaDerby pderby;
    FilmeDerby fderby;
    Statement stmt;
    
    
    
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        pderby = new PessoaDerby();
        fderby = new FilmeDerby();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        addcliente = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        jcNome = new javax.swing.JTextField();
        sobrenome = new javax.swing.JLabel();
        jcSobrenome = new javax.swing.JTextField();
        idade = new javax.swing.JLabel();
        jcIdade = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        jcId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jfNome = new javax.swing.JTextField();
        jcSalvar = new javax.swing.JButton();
        jcListar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jfGenero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jfNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jfExemplares = new javax.swing.JTextField();
        jfSalvar = new javax.swing.JButton();
        jfListar = new javax.swing.JButton();
        jcRemover = new javax.swing.JButton();
        jfRemover = new javax.swing.JButton();
        jInstrucoes = new javax.swing.JButton();
        jcBuscarNome = new javax.swing.JButton();
        jcBuscarSobrenome = new javax.swing.JButton();
        jcBuscarIdade = new javax.swing.JButton();
        jcBuscarId = new javax.swing.JButton();
        jfBuscarNome = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jAlugarCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jAlugarFilme = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jAlugarExemplar = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addcliente.setText("CLIENTE:");

        nome.setText("Nome:");

        jcNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcNomeActionPerformed(evt);
            }
        });

        sobrenome.setText("Sobrenome:");

        idade.setText("Idade:");

        id.setText("Numero de Identificação:");

        jLabel1.setText("FILME:");

        jLabel2.setText("Nome:");

        jcSalvar.setText("SALVAR");
        jcSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcSalvarActionPerformed(evt);
            }
        });

        jcListar.setText("LISTAR");
        jcListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcListarActionPerformed(evt);
            }
        });

        jLabel3.setText("Genero:");

        jLabel4.setText("Numero de Identificação:");

        jLabel5.setText("Numero de Exemplares:");

        jfSalvar.setText("SALVAR");
        jfSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfSalvarActionPerformed(evt);
            }
        });

        jfListar.setText("LISTAR");
        jfListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfListarActionPerformed(evt);
            }
        });

        jcRemover.setText("REMOVER");
        jcRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcRemoverActionPerformed(evt);
            }
        });

        jfRemover.setText("REMOVER");
        jfRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfRemoverActionPerformed(evt);
            }
        });

        jInstrucoes.setText("INSTRUÇÕES");
        jInstrucoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInstrucoesActionPerformed(evt);
            }
        });

        jcBuscarNome.setText("BUSCAR");
        jcBuscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBuscarNomeActionPerformed(evt);
            }
        });

        jcBuscarSobrenome.setText("BUSCAR");
        jcBuscarSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBuscarSobrenomeActionPerformed(evt);
            }
        });

        jcBuscarIdade.setText("BUSCAR");
        jcBuscarIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBuscarIdadeActionPerformed(evt);
            }
        });

        jcBuscarId.setText("BUSCAR");
        jcBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBuscarIdActionPerformed(evt);
            }
        });

        jfBuscarNome.setText("BUSCAR");
        jfBuscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfBuscarNomeActionPerformed(evt);
            }
        });

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("BUSCAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BUSCAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("ALUGAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("DEVOLVER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Numero Cliente:");

        jLabel7.setText("Numero Filme:");

        jLabel8.setText("Numero do Exemplar:");

        jButton6.setText("CHECAR CLIENTE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("CHECAR FILME");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jcSobrenome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcIdade, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcId, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addcliente)
                        .addComponent(nome)
                        .addComponent(sobrenome)
                        .addComponent(idade)
                        .addComponent(id)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jcSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jcListar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jcRemover)))
                    .addComponent(jcNome)
                    .addComponent(jInstrucoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcBuscarNome)
                            .addComponent(jcBuscarSobrenome)
                            .addComponent(jcBuscarIdade)
                            .addComponent(jcBuscarId))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jfGenero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jfSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jfListar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jfRemover))
                            .addComponent(jfExemplares, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jfBuscarNome)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAlugarExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jAlugarFilme, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addComponent(jAlugarCliente)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfBuscarNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jfGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addcliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nome)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcBuscarNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sobrenome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcBuscarSobrenome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idade)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcBuscarIdade)
                            .addComponent(jfNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcBuscarId)
                            .addComponent(jfExemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcSalvar)
                            .addComponent(jcListar)
                            .addComponent(jcRemover)
                            .addComponent(jfSalvar)
                            .addComponent(jfListar)
                            .addComponent(jfRemover))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jInstrucoes)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAlugarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAlugarFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAlugarExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcSalvarActionPerformed
        
        int check = 0;
        /*String instrucao = "SELECT * FROM PESSOA";
        try{
            ResultSet rs = stmt.executeQuery(instrucao);
            while (rs.next()){
                if(jcId.getText() == rs.getString("ID")){
                    check = 1;                
                }
            }
        }catch(SQLException se){
            System.out.println("Mensagem: " + se.getMessage());
        }*/
        
        if( check == 0 ){       
            Pessoa p = new Pessoa(jcNome.getText(), jcSobrenome.getText(), Integer.parseInt(jcIdade.getText()), Integer.parseInt(jcId.getText()));
        pderby.adicionar(p);
        }else{
            System.out.println("Ja existe um cliente com este codigo, favor escolher outro codigo!");
        }
    }//GEN-LAST:event_jcSalvarActionPerformed

    private void jcNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcNomeActionPerformed

    private void jfSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfSalvarActionPerformed
        Filme f = new Filme(jfNome.getText(), jfGenero.getText(), Integer.parseInt(jfNum.getText()), Integer.parseInt(jfExemplares.getText()));
        fderby.adicionar(f);
    }//GEN-LAST:event_jfSalvarActionPerformed

    private void jcListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcListarActionPerformed
        pderby.listarTudo();
    }//GEN-LAST:event_jcListarActionPerformed

    private void jfListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfListarActionPerformed
        fderby.listarTudo();
    }//GEN-LAST:event_jfListarActionPerformed

    private void jfRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfRemoverActionPerformed
        String codigo = jfNum.getText();
        fderby.remover(Integer.parseInt(codigo));
    }//GEN-LAST:event_jfRemoverActionPerformed

    private void jcRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcRemoverActionPerformed
        String codigo = jcId.getText();
        pderby.remover(Integer.parseInt(codigo));
    }//GEN-LAST:event_jcRemoverActionPerformed

    private void jInstrucoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInstrucoesActionPerformed
        System.out.println("PARA ADICIONAR UM CLIENTE, PREENCHA TODOS OS CAMPOS DE CLIENTE E PRESSIONE SALVAR.");
        System.out.println("PARA ADICIONAR UM FILME, PREENCHA TODOS OS CAMPOS DE FILME E PRESSIONE SALVAR.\n");
        
        System.out.println("PARA REMOVER UM CLIENTE, PREENCHA O CAMPO NUMERO DE IDENTIFICAÇÃO EM CLIETE E PRESSIONE REMOVER.");
        System.out.println("PARA REMOVER UM FILME, PREENCHA O CAMPO NUMERO DE IDENTIFICAÇÃO EM FILME E PRESSIONE REMOVER.\n");
        
        System.out.println("PARA LISTAR TODOS OS FILMES OU CLIENTES, PRESSIONE LISTAR NO SEU DEVIDO CAMPO.\n");
        
        System.out.println("PARA ALUGAR UM FILME, PREENCHA AMBOS OS CAMPOS NUMERO DE IDENTIFICAÇÃO, SELECIONE UM EXEMPLAR E PRESSIONE ALUGAR.");
        System.out.println("CASO EXISTA UM EXEMPLAR DISPONÍVEL, O SISTEMA SEMPRE IRÁ ALUGAR O EXEMPLAR PARA O DEVIDO CLIENTE.\n");
                
        System.out.println("PARA RECEBER UM EXEMPLAR QUE UM CLIENTE ALUGOU, PREENCHA O CAMPO NUMERO DE IDENTIFICAÇÃO E EXEMPLAR EM FILME E PRESSIONE DEVOVER.\n");
        System.out.println("A FUNÇÃO CHECAR CLIENTE VERIFICA SE UM DETERMINADO CLIENTE ESTÁ COM ALGUM FILME ALUGADO.");    
        System.out.println("A FUNÇÃO CHECAR FILME VERIFICA SE UM DETERMINADO FILME ESTÁ COM ALGUM EXEMPLAR EMPRESTADO PARA ALGUM CLIENTE.");
        System.out.println("PARA CHECAR, PREENCHA O CAMPO NUMERO DE IDENTIFICAÇÃO EM CLIENTE OU FILME, DEPOIS PRESSIONE CHECAR CLIENTE OU CHECAR FILME.\n");
        
        System.out.println("TODOS OS CAMPOS TEM A OPÇÃO BUSCAR, PARA LISTAR POR CAMPO, DIGITE O QUE DESEJA BUSCAR NO CAMPO E CLIQUE EM BUSCAR.");
        System.out.println("A BUSCA DIFERENCIA ACENTOS E CARACTERES, DIGITE CORRETAMENTE!\n");
        
    }//GEN-LAST:event_jInstrucoesActionPerformed

    private void jcBuscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBuscarNomeActionPerformed
        pderby.listarNome(jcNome.getText());
    }//GEN-LAST:event_jcBuscarNomeActionPerformed

    private void jcBuscarSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBuscarSobrenomeActionPerformed
        pderby.listarSobrenome(jcSobrenome.getText());
    }//GEN-LAST:event_jcBuscarSobrenomeActionPerformed

    private void jcBuscarIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBuscarIdadeActionPerformed
        pderby.listarIdade(jcIdade.getText());
    }//GEN-LAST:event_jcBuscarIdadeActionPerformed

    private void jcBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBuscarIdActionPerformed
        pderby.listarId(jcId.getText());
    }//GEN-LAST:event_jcBuscarIdActionPerformed

    private void jfBuscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfBuscarNomeActionPerformed
        fderby.listarNome(jfNome.getText());
    }//GEN-LAST:event_jfBuscarNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fderby.listarGenero(jfGenero.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fderby.listarNum(jfNum.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        fderby.listarExemplares(jfExemplares.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        fderby.alugar(jAlugarCliente.getText(), jAlugarFilme.getText(), jAlugarExemplar.getText());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        fderby.devolver(jAlugarFilme.getText(), jAlugarExemplar.getText());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        pderby.checarCliente(jAlugarCliente.getText());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        fderby.checarFilme(jAlugarFilme.getText(), jAlugarExemplar.getText());
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addcliente;
    private javax.swing.JLabel id;
    private javax.swing.JLabel idade;
    private javax.swing.JTextField jAlugarCliente;
    private javax.swing.JTextField jAlugarExemplar;
    private javax.swing.JTextField jAlugarFilme;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jInstrucoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jcBuscarId;
    private javax.swing.JButton jcBuscarIdade;
    private javax.swing.JButton jcBuscarNome;
    private javax.swing.JButton jcBuscarSobrenome;
    private javax.swing.JTextField jcId;
    private javax.swing.JTextField jcIdade;
    private javax.swing.JButton jcListar;
    private javax.swing.JTextField jcNome;
    private javax.swing.JButton jcRemover;
    private javax.swing.JButton jcSalvar;
    private javax.swing.JTextField jcSobrenome;
    private javax.swing.JButton jfBuscarNome;
    private javax.swing.JTextField jfExemplares;
    private javax.swing.JTextField jfGenero;
    private javax.swing.JButton jfListar;
    private javax.swing.JTextField jfNome;
    private javax.swing.JTextField jfNum;
    private javax.swing.JButton jfRemover;
    private javax.swing.JButton jfSalvar;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel sobrenome;
    // End of variables declaration//GEN-END:variables
}
